# Generated by Django 4.0.1 on 2024-08-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
