# Generated by Django 4.0.1 on 2024-08-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_profile_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registered_by_google',
            field=models.BooleanField(default=False),
        ),
    ]
