# Generated by Django 4.0.1 on 2024-08-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_registered_by_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img_url',
            field=models.URLField(blank=True, default='https://static.vecteezy.com/system/resources/previews/002/318/271/non_2x/user-profile-icon-free-vector.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='raw_password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
