# Generated by Django 4.0.1 on 2024-08-01 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
